server:
  port: 18080
spring:
  application:
    name: ai_study
  ai:
    openai:
      # api-key添加自己生成的key
      api-key: sk-71926b8e34c94b24b8bf4bac8ee5bac9
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          #temperature参数用于控制生成文本的多样性。具体来说值越高，生成的文本越多样化，但也可能包含更多的随机性和不可预测的内容；值越低，生成的文本越接近于确定性的结果，即生成的文本会更加一致和可预测。
          temperature: 0.5